name: dev 
on: 
  push: 
    branches: [ dev ] 
  pull_request: 
    branches: [ dev ] 
    
 jobs: 
   build: 
     runs-on: macos-12 
     steps: 
     - uses: actions/checkout@v2 
     - name: make 
       run: make
